### ISSUE TITLE
Build warnings on Windows

### ISSUE THREAD

**Issue by pachadotdev** [litalbarkai/redatam-converter#3]
Hi

I managed to build this locally on Windows with VS19.

When I build it says: `D:\a\redatam-converter\redatam-converter\src\readers\FuzzyVariableParser.cpp(247,25): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data`

According to https://stackoverflow.com/questions/6578048/size-t-vs-int-warning, I wouldn't care much about it

**Comment by litalbarkai** [comment]
This conversion repeats in multiple places but shouldn't be a problem since the argument's size shouldn't be larger than MAX_INT and if it is the program will probably fail elsewhere. The use of size_t is because the position in the byte array should always be positive so GetPos will always return a positive value, whereas SetPos recieves an int since it might get a position which is out of bounds and then it will throw an out_of_range exception
